### ISSUE TITLE
Are these two mappings conflict?

### ISSUE THREAD

**Issue by chaoqunya** [jdhao/nvim-config#105]
https://github.com/jdhao/nvim-config/blob/40fa9aab1cbd9ce176140d733ec7157fa7e0a5b6/core/mappings.lua#L7-L11

I have checked elder commits about these two mappings and guess the second mapping should be `<c-t>`? 

But I am very new to neovim so I'm not sure.

**Comment by jdhao** [comment]
yeah, good catch! The second should be `<c-t>`, I made a mistake in a hurry to convert viml mapping to lua 😃

**Comment by jdhao** [comment]
Can you make a PR to fix this? Thanks

**Comment by jdhao** [comment]
close in #106
