### ISSUE TITLE
XkbSwitchLib missing on mac big sur

### ISSUE THREAD

**Issue by marcelned** [jdhao/nvim-config#11]
<img width="855" alt="Screenshot 2021-06-16 at 20 35 49" src="https://user-images.githubusercontent.com/82392567/122274078-74a78b00-cee2-11eb-972b-f483ffbd4db1.png">

**Comment by jdhao** [comment]
Just install it if you need it or comment out the relevant plugins.

**Comment by jdhao** [comment]
Also your Nvim version is too old. I am testing my config against the latest nightly release.
