### ISSUE TITLE
Icon not being shown

### ISSUE THREAD

**Issue by morpheuslord** [jdhao/nvim-config#148]
I am using nvim in my windows but when I try to launch my nvim window I get a question mark instead of the icon how can I fix this what is the <leader> key and where is it in windows ??

**Comment by jdhao** [comment]
What do you mean by the question mark? Can you take a snapshot?

**Comment by jdhao** [comment]
You have not installed the patched font for your terminal, as instructed by the installation guide [here](https://github.com/jdhao/nvim-config/blob/master/docs/README.md#patched-fonts).
