### ISSUE TITLE
Indentation style

### ISSUE THREAD

**Issue by fvcci** [jdhao/nvim-config#151]
Hi! I have been using your config for a while and really love it! There is just one small caveat though, which is that your indentation style is different from mine.

Specifically, your config prefers to indent multiline arguments and expressions to brackets like this:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/71908175/199890524-c97be7b9-ac24-4ab7-989f-8b04e326a8b4.png">

When I would like to have it like this:
<img width="164" alt="image" src="https://user-images.githubusercontent.com/71908175/199891063-907742df-b660-4565-8a3e-753a69fe15cf.png">

I have tried searching the files to configure the indentation to my liking, but ended up coming up with nothing so I finally caved in and made a "Feature request" to ask where I can change this indentation style. Many thanks!

**Comment by jdhao** [comment]
You can config a formatter for this, like `black` or `yapf`.  Use [neoformat](https://github.com/sbdchd/neoformat) or [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) for this.
