### ISSUE TITLE
Unsupported nvim version 

### ISSUE THREAD

**Issue by 0xMrR0b0t** [jdhao/nvim-config#153]
**Error detected while processing /root/.config/nvim/init.lua:
Unsupported nvim version: expect 0.8.0, but got 0.7.2 instead!**

![image](https://user-images.githubusercontent.com/53564887/200114802-b5dadb30-9829-4a35-a651-bce77982f171.png)

**Comment by jdhao** [comment]
The error message is pretty clear. You need to install nvim 0.8 to use thid config.
