### ISSUE TITLE
arrow keys not working

### ISSUE THREAD

**Issue by DevAgarwal223** [jdhao/nvim-config#182]
- `nvim --version`: 
- terminal emulator and version:
- Operating system/version:
- Have you read and followed all steps in the [doc](https://github.com/jdhao/nvim-config/tree/master/docs):
- Output of command `set runtimepath`:

  
  ```

  ```

**Describe the bug**

Steps to reproduce the issue:

1.
2.
3.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jdhao** [comment]
they are remapped for other usage: https://github.com/jdhao/nvim-config/blob/master/core/mappings.lua#L164
