### ISSUE TITLE
nvim 0.9+ track

### ISSUE THREAD

**Issue by jdhao** [jdhao/nvim-config#192]
1. `vim.iter`: https://github.com/neovim/neovim/commit/ab1edecfb7c73c82c2d5886cb8e270b44aca7d01
2. `vim.keycode`: https://github.com/neovim/neovim/commit/7e70ca0b4808bb9d8f19c28c8f93e8f2b9e0d0f0
3. inline virtual text: https://github.com/neovim/neovim/commit/efa9b299a7cb68909e9bcd290e4d12bcb6d0bb03. One use case is LSP inlay hints.
4. `vim.loop` renamed to `vim.uv`: https://github.com/neovim/neovim/commit/2db719f6c2b677fcbc197b02fe52764a851523b2
5. `vim.system()`: https://github.com/neovim/neovim/commit/c0952e62fd0ee16a3275bb69e0de04c836b39015
6. abbreviation support in `nvim_set_keymap()`: https://github.com/neovim/neovim/commit/42bbc4fabcf948ac6b8798b8992bcba1fc1d3e59
7. inlay hint support in nvim lsp: https://github.com/neovim/neovim/commit/643546b82b4bc0c29ca869f81af868a019723d83
8. support Super and Meta keys
https://github.com/neovim/neovim/pull/24357
9. neovim can show documentation for vim.fn.xxx now
https://github.com/neovim/neovim/commit/42333ea98dfcd2994ee128a3467dfe68205154cd
10. You can now use `fclose` command to close floating windows
https://github.com/neovim/neovim/commit/372aa2eb3db375385cf19dc0a6571f790b858241
11. base64 module added
https://github.com/neovim/neovim/commit/224f303ee54c54d2147f03010385e8cc48e42869
12. native OSC 52 support
https://github.com/neovim/neovim/commit/748bc4d22d35b40f0795015e5d93113b526adf22
13. Neovim-branded default colorscheme
https://github.com/neovim/neovim/commit/64a14026d76ba1798d91e15a941fcb6af7cbc5ad
14. builtin support for commenting code
https://github.com/neovim/neovim/commit/73de98256cf3932dca156fbfd0c82c1cc10d487e
15. `grepprg` now use ripgrep if available
https://github.com/neovim/neovim/commit/20b38677c22b0ff19ea54396c7718b5a8f410ed4

**Comment by kutsan** [comment]
This is great, thanks!
