### ISSUE TITLE
Some icons missing

### ISSUE THREAD

**Issue by jdev082** [jdhao/nvim-config#200]
Some icons are there, but a majority are gone. I have a patched nerd font installed, and the one I have set is "FiraCode Nerd Font", I also tried "SourceCodePro Nerd Font". Neither display most of the icons I am using the kitty terminal, same issue with Konsole.

main screen:
![image](https://github.com/jdhao/nvim-config/assets/92550746/cb3214bf-99c8-4567-98a8-9b2da84d3a16)

when opening a file:
![image](https://github.com/jdhao/nvim-config/assets/92550746/4e58e82f-4cf5-4db5-aa09-24173ae629dd)

**Comment by jdhao** [comment]
What is your System? The Template is there for a reason. I think it is due to font issues almost 100%. You meed to figure out why.
