### ISSUE TITLE
Error detected while processing config/nvim/core/globals.vim

### ISSUE THREAD

**Issue by double-trouble2** [jdhao/nvim-config#22]
Good day to all. I did everything according to the instructions from [here](https://jdhao.github.io/nvim-config/docs/).

As soon as I have installed all the dependencies and try to run and install plugins, it gives such errors:

`Error detected while processing /home/islombek/.config/nvim/core/globals.vim:`
`line   33:`
`Python 3 executable not found! You must install Python 3 and set its PATH correctly!`
`Installing packer.nvim`
`Error detected while processing /home/islombek/.config/nvim/core/plugins.vim:`
`line    4:`
`E5108: Error executing lua /home/islombek/.config/nvim/lua/plugins.lua:23: Vim(packadd):E919: Directory not found in` `'packpath': "pack/`
`*/opt/packer.nvim"`
`line  482:`
`E117: Unknown function: wilder#enable_cmdline_enter`
`line  488:`
`E117: Unknown function: wilder#set_option`
`line  490:`
`E117: Unknown function: wilder#python_difflib_sorter`
`E116: Invalid arguments for function wilder#cmdline_pipeline`
`E116: Invalid arguments for function wilder#branch`
`E116: Invalid arguments for function wilder#set_option`
`line  505:`
`E117: Unknown function: wilder#basic_highlighter`
`E116: Invalid arguments for function wilder#wildmenu_airline_theme`
`E116: Invalid arguments for function wilder#wildmenu_renderer`
`E116: Invalid arguments for function wilder#set_option`
`Error detected while processing function 11:`
`line    1:`
`E919: Directory not found in 'packpath': "pack/*/opt/doom-one.nvim"`
`Error detected while processing command line:`
`E492: Not an editor command: PackerInstall`

Cloning into '/home/islombek/.local/share/nvim/site/pack/packer/opt/packer.nvim'...
fatal: unable to access 'https://hub.fastgit.org/wbthomason/packer.nvim/': The requested URL returned error: 429

[Process exited 128]

I tried to use a bash script, and there are such errors:

`++ echo 'Setting up config and installing plugins'`
`Setting up config and installing plugins`
`++ [[ -d /root/.config/nvim ]]`
`++ mv /root/.config/nvim /root/.config/nvim.backup`
`mv: inter-device move failed: '/root/.config/nvim' to '/root/.co`
`kup/nvim'; unable to remove target: Directory not empty`

I have a linux(debian bullseye) system. Please help me figure this out.

**Comment by double-trouble2** [comment]
I'm not very friendly with python, I had to remove this quick launch in python 3_host_prog. Thank you very much the plugins have been installed, the editor has started with your config!

**Comment by jdhao** [comment]
@double-trouble2  LeaderF requires Python to run effectively. You need to set up Python. Or you can use telescope, which is also included in this config, but I haven't bind any key binding to it. You can call telescope via command `:Telescope find_files`.

**Comment by jdhao** [comment]
Fastgit is removed on https://github.com/jdhao/nvim-config/commit/15dfccf81ee7e78836d4f65f9a81eb400b0f1b08.
