### ISSUE TITLE
How to delete the random color theme for this config?

### ISSUE THREAD

**Issue by powerLEO101** [jdhao/nvim-config#226]
I am sorry, I am very new to neovim. I cannot find where in your config file to delete the random color theme each time opening a file?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jdhao** [comment]
The random color scheme function is defined and used [here](https://github.com/jdhao/nvim-config/blob/4dc2d9575bb35f5a3951d1289c02d1826ad72eb2/lua/colorschemes.lua#L122-L143).

**Comment by powerLEO101** [comment]
Thanks a lot!
