### ISSUE TITLE
disable autobracket?

### ISSUE THREAD

**Issue by powerLEO101** [jdhao/nvim-config#227]
Hello, sorry to bother you again.

I want to disable the autobracket for editing. Did you accomplish autobracket with a plguin? or config files?

Thanks!

Leo

**Comment by jdhao** [comment]
I am using delimitMate to auto insert pairs: https://github.com/jdhao/nvim-config/blob/63ff776758996733e747ff4ffa5c1c3f05cebc8a/lua/plugins.lua#L226-L226
