### ISSUE TITLE
The error handling at plug_url_format doesn't actually work

### ISSUE THREAD

**Issue by z0xyz** [jdhao/nvim-config#24]
I have no knowledge whatsoever about lua , but at `~/.config/nvim/lua/plugins.lua` with the if else statement encompassing the variable `plug_url_format` didn't work 
When i tried install the plugins for the first time , i issue the command `PackerInstall` `packer` tried to fetch the repositories from fastgit.org which resulted in `failed to install`  with `503 error` being the cause of the proplem behind the scene .
Therefore I suggest that github.com should be placed prior to fastgit.org in the if else statement .

**Comment by jdhao** [comment]
@z0xyz Just change the code locally.  Changing from fastgit to github fails for me.

**Comment by z0xyz** [comment]
I did , but just wanted to point this quirk out .

**Comment by jdhao** [comment]
> @jdhao I did , but just wanted to point this quirk out .

This is not a quirk, this a feature 🐈. Ever wonder why I put fastgit in the first place? Github connection is not good in China.I have to do this 😅

**Comment by z0xyz** [comment]
@z0xyz  But the conditional checking of the availability of the repositories at either platform needs to be enhanced , as i pointed out it the if else statement went along with fastgit even though it returns 503 error (which i assume would be the case for many others based on their geolocation) .
I'm fine with either platform , as long as the script checks which one returns the desired repos .

**Comment by jdhao** [comment]
@z0xyz  I use fastgit for Linux only because I use a Linux server and I can not change its proxy settings. For Windows and macOS, I use github as I can change proxy settings on these two platforms.

> But the conditional checking of the availability of the repositories at either platform needs to be enhanced ,

I am happy to change, provided that your solution does not break my environment.

**Comment by z0xyz** [comment]
@jdhao  Thanks !

**Comment by jdhao** [comment]
fastgit removed in https://github.com/jdhao/nvim-config/commit/15dfccf81ee7e78836d4f65f9a81eb400b0f1b08
