### ISSUE TITLE
SSH connection closes when running `nvim`

### ISSUE THREAD

**Issue by FountainOfInk** [jdhao/nvim-config#240]
- nvim version: NVIM v0.9.2
- terminal emulator and version : kitty 0.29.2 created by Kovid Goyal
- Ubuntu 23.04 (Lunar Lobster) (via ssh)
- Have you read and followed all steps in the [doc](https://github.com/jdhao/nvim-config/tree/master/docs): Yes.
- Output of command `set runtimepath`: `[output is entirely empty]`

  
  `
/home/user/.local/share/bob/nvim-bin/nvim
  `

**Describe the bug**

On my (small, limited) Ubuntu vps, after `git clone`ing the config, and running `nvim`, the ssh connection closes (while doing what seems to be installing plugins)
Steps to reproduce the issue:

1. Clone the config
2. Run `nvim`
3. Observe `[No Name]Shared connection to [vps ip address] closed.
**Expected behavior**

`nvim` does not terminate my ssh session.

**Screenshots**

**Additional context**

**Comment by jdhao** [comment]
I have never experienced this. I guess this is not related to my config.

**Comment by FountainOfInk** [comment]
> I have never experienced this. I guess this is not related to my config, most probably due to your system.

Tried it on my laptop, works fine, I'm assuming that this is because of the limited resources on the VPS.
