### ISSUE TITLE
hide lsp processing massage 

### ISSUE THREAD

**Issue by AhmadNaruto** [jdhao/nvim-config#246]
iam using this config and working great. but unfortunately when using in termux (Android) Lsp processing massage (bottom right corner) quite annoying and covers the code.
I wish there was a way or option to hide the message.

![IMG_20231006_075045](https://github.com/jdhao/nvim-config/assets/47007634/fe408dc3-7fed-4d59-9948-3593d0fafb87)

I know this is more of a question than a feature request. but I think it's quite important. because I code more often on a smartphone than on a PC

**Comment by jdhao** [comment]
The progress hint is from fidget.nvim, you can remove it to disable the feature: https://github.com/jdhao/nvim-config/blob/master/lua/plugins.lua#L485
