### ISSUE TITLE
Failed to run `config` for indent-blankline

### ISSUE THREAD

**Issue by yxsongbo** [jdhao/nvim-config#247]
Failed to run `config` for indent-blankline.nvi
m

/Users/songbo/.config/nvim/lua/config/indent-bl
ankline.lua:5: module 'ibl' not found:
^Ino field package.preload['ibl']
cache_loader: module ibl not found
cache_loader_lib: module ibl not found
^Ino file './ibl.lua'
^Ino file '/usr/local/share/luajit-2.1.0-beta3/
ibl.lua'
^Ino file '/usr/local/share/lua/5.1/ibl.lua'
^Ino file '/usr/local/share/lua/5.1/ibl/init.lu
a'
^Ino file './ibl.so'
^Ino file '/usr/local/lib/lua/5.1/ibl.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - .config/nvim/lua/config/indent-blankline.lu
a:5
  - .config/nvim/lua/plugins.lua:175 _in_ **con
fig**
Press ENTER or type command to continue

  
  ```

  ```

**Describe the bug**

Steps to reproduce the issue:

1.
2.
3.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jdhao** [comment]
Try to delete the plugin indent-blankline and reinstall it again. Please use the latest code of this repo.

**Comment by devgiri0082** [comment]
I also got the same issue. I am using macbook air, m1 2020 with mac os 13.4.

**Comment by carlosnsr** [comment]
`:Lazy update indent-blankline.nvim` fixed it for me

I still had v2.20 installed.  The new config is for v3+ (I assume).  Updating to the latest version of `indent-blankline` using the above command solved it.
