### ISSUE TITLE
Open directory with nvim

### ISSUE THREAD

**Issue by mast9rmind** [jdhao/nvim-config#257]
Looks like the `nvim .` for opening directory doesn't work, however it's a default command of nvim?
what's replacement.

**Comment by jdhao** [comment]
Hello @mast9rmind , according to documentation [here](https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup), you can add the following code to `lua/custom-autocmd.lua` of this configuration:

```lua
local function open_nvim_tree(data)

  -- buffer is a directory
  local directory = vim.fn.isdirectory(data.file) == 1

  if not directory then
    return
  end

  -- create a new, empty buffer
  vim.cmd.enew()

  -- wipe the directory buffer
  vim.cmd.bw(data.buf)

  -- change to the directory
  vim.cmd.cd(data.file)

  -- open the tree
  require("nvim-tree.api").tree.open()
end

vim.api.nvim_create_autocmd({ "VimEnter" }, { callback = open_nvim_tree })
```

I tested it and it works fine.
