### ISSUE TITLE
make tab as tab

### ISSUE THREAD

**Issue by gorliver** [jdhao/nvim-config#268]
First, thank you for the nvim config. I enjoy it very much!
How can I change tab as tab? I'm asking because two space rise errors for regex "\t" and it is not possible for me to change the "\t" to "\s+".
Many thanks!

**Comment by gorliver** [comment]
Sorry for the confusion.
Nvim with this config converts a tab to two spaces. In the following file, I input a tab between `L01` and `/share`. It turns out that nvim put two spaces between `L01` and `/share` instead of a tab.
![image](https://github.com/jdhao/nvim-config/assets/15271446/cc6ba235-7508-4801-8be7-792efd9e0e63)

I would like a real tab between the two strings like this:
![image](https://github.com/jdhao/nvim-config/assets/15271446/2720dcfb-2ec9-4f5e-8685-5006858daf95)

**Comment by jdhao** [comment]
All tab-related options is placed currently here: https://github.com/jdhao/nvim-config/blob/050eacaee27272fa893ea8c0d7279625a05319aa/viml_conf/options.vim#L43-L46.  You can customize based on your need.
