### ISSUE TITLE
Fugitive.vim doesnt exists?

### ISSUE THREAD

**Issue by c0del1ar** [jdhao/nvim-config#269]
I checked in lazyvim that the vim-fugitive is already installed, but while i tried type `Git` command, it doesnt exist. It only another Git blabla command showing in pipeline.

![240222_23h00m11s_screenshot](https://github.com/jdhao/nvim-config/assets/49186597/cbe98797-87e2-44d6-ae31-0091ef7e7c32)

**Comment by jdhao** [comment]
The fugitive plugin is only activated when certain conditions are met. Are you sure it is started already??

**Comment by c0del1ar** [comment]
all should working correctly, i dont know what happened but it solved by using packer
