### ISSUE TITLE
Wilder not working properly 

### ISSUE THREAD

**Issue by AlgumCorrupto** [jdhao/nvim-config#272]
- `nvim --version`: v0.9.5
- terminal emulator and version: nvim-qt/cmd
- Operating system/version: Windows 11
- Have you read and followed all steps in the [doc](https://github.com/jdhao/nvim-config/tree/master/docs): Yes
- Output of command `set runtimepath`:

```runtimepath=~\AppData\Local\nvim,~\AppData\Local\nvim-data\plugged\wilder.nvim,~\AppData\Local\nvim-data\plugged\nvim-yarp,~\AppData\Local\nvim-data\plugged\vim-hug-neovim-rpc,~\AppData\Local\nvim-data\lazy\lazy.nvim,~/AppData/Local/nvim-data/lazy/nvim-notify,~\AppData\Local\nvim-data\lazy\unicode.vim,~\AppData\Local\nvim-data\lazy\whitespace.nvim,~\AppData\Local\nvim-data\lazy\vim-swap,~\AppData\Local\nvim-data\lazy\fidget.nvim,~\AppData\Local\nvim-data\lazy\cmp-nvim-ultisnips,~\AppData\Local\nvim-data\lazy\cmp-emoji,~\AppData\Local\nvim-data\lazy\cmp-omni,~\AppData\Local\nvim-data\lazy\cmp-buffer,~\AppData\Local\nvim-data\lazy\cmp-path,~\AppData\Local\nvim-data\lazy\lspkind-nvim,~\AppData\Local\nvim-data\lazy\cmp-nvim-lsp,~\AppData\Local\nvim-data\lazy\nvim-cmp,~\AppData\Local\nvim-data\lazy\vim-highlighturl,~\AppData\Local\nvim-data\lazy\nvim-web-devicons,~\AppData\Local\nvim-data\lazy\which-key.nvim,~\AppData\Local\nvim-data\lazy\indent-blankline.nvim,~\AppData\Local\nvim-data\lazy\vim-repeat,~\AppData\Local\nvim-data\lazy\vim-indent-object,~\AppData\Local\nvim-data\lazy\vim-commentary,~\AppData\Local\nvim-data\lazy\vim-sandwich,~\AppData\Local\nvim-data\lazy\hop.nvim,~\AppData\Local\nvim-data\lazy\open-browser.vim,~\AppData\Local\nvim-data\lazy\targets.vim,~\AppData\Local\nvim-data\lazy\lualine.nvim,~\AppData\Local\nvim-data\lazy\bufferline.nvim,~\AppData\Local\nvim-data\lazy\onedarkpro.nvim,~\AppData\Local\nvim-data\lazy\dressing.nvim,~\AppData\Local\nvim-data\lazy\plenary.nvim,~\AppData\Local\nvim-data\lazy\git-conflict.nvim,~\AppData\Local\nvim-data\lazy\gitsigns.nvim,~\AppData\Local\nvim-data\lazy\headlines.nvim,~\AppData\Local\nvim-data\lazy\wilder.nvim,~\AppData\Local\nvim-data\lazy\diffview.nvim,~\AppData\Local\nvim-data\lazy\dashboard-nvim,~\scoop\apps\neovim\current\share\nvim\runtime,~\scoop\apps\neovim\current\lib\nvim,~\AppData\Local\nvim-data\lazy\cmp-nvim-ultisnips\after,~\AppData\Local\nvim-data\lazy\cmp-emoji\after,~\AppData\Local\nvim-data\lazy\cmp-omni\after,~\AppData\Local\nvim-data\lazy\cmp-buffer\after,~\AppData\Local\nvim-data\lazy\cmp-path\after,~\AppData\Local\nvim-data\lazy\cmp-nvim-lsp\after,~\AppData\Local\nvim-data\lazy\indent-blankline.nvim\after,~\AppData\Local\nvim-data\lazy\vim-sandwich\after,~\AppData\Local\nvim-data\lazy\onedarkpro.nvim\after,~\AppData\Local\nvim\after,~\AppData\Local\nvim-data\lazy\readme```

**Describe the bug**

Nvim throws error: ``pipeline: Vim(call):E117: Unknown function: _wilder_python_difflib_sort`` when typing commands

Steps to reproduce the issue:

1. fresh install of nvim + this config file and running the powershell installation
2. Python installed from official website + pynvim
3. Testing Nvim commands

**Expected behavior**
![image](https://github.com/jdhao/nvim-config/assets/112904295/43ecbb94-10e7-45ee-a0c9-656356604e41)

**Bug**
![image](https://github.com/jdhao/nvim-config/assets/112904295/4d157366-a6ea-4160-bd87-349eebc5b860)

**Additional Context**
Runtimepath shows ``plugged/wilder.nvim`` because i've also tested with others plugin managers

**Comment by AlgumCorrupto** [comment]
![image](https://github.com/jdhao/nvim-config/assets/112904295/f5561682-25c9-4e07-9e73-33aaa4eae8b4)

Exact same setup in an Ubuntu VM

**Comment by jdhao** [comment]
1. Have you installed Python3 and pynvim on Windows? What is the output of `pip3 list`? Does it include pynvim?
2. Have you checked that `$NVIM_DATA/rplugin.vim` contains functions for wilder.nvim? `$NVIM_DATA` is the the directory where nvim stores its data, the exact path can be checked via cmd line command `:echo stdpath('data')`

**Comment by simoneSantoni** [comment]
![image](https://github.com/jdhao/nvim-config/assets/12460460/f0d2d779-50e9-4339-bf37-4fba3367c146)
Same problem on Windows 11

**Comment by AlgumCorrupto** [comment]
I just saw the message. When I get home i'm gonna test it. I'm sure pyvim was installed correctly because when I ``checkhealth``, no errors related to python or pyvim appear. 
By the way on Windows, ``python3`` and ``pip3`` are called just ``python`` and ``pip``.

**Comment by AlgumCorrupto** [comment]
1. output of pip3 list:
```
Package         Version
--------------- -----------
contourpy       1.2.0
cycler          0.12.1
fonttools       4.50.0
kiwisolver      1.4.5
matplotlib      3.8.3
numpy           1.26.4
packaging       24.0
pillow          10.2.0
pip             24.0
pyparsing       3.1.2
PyQt6           6.6.1
PyQt6-Qt6       6.6.2
PyQt6-sip       13.6.0
python-dateutil 2.9.0.post0
six             1.16.0
```

2. ``..../nvim-data/rplugin.vim`` file:
```
" perl plugins


" node plugins


" ruby plugins


" python plugins



```

**Comment by AlgumCorrupto** [comment]
seems like it is in fact running, but not producing the intended output
``$NVIM_DATA/rplugin.vim`` still goes like this: 
```
" perl plugins


" node plugins


" python3 plugins


" ruby plugins


" python plugins


```
output of ``UpdateRemotePlugins``
![image](https://github.com/jdhao/nvim-config/assets/112904295/0297315e-04a5-4c16-bc35-c6042ad687eb)

**Comment by jdhao** [comment]
Then something in your system is broken, but I don't know what. You need to debug yourself.

**Comment by pro470** [comment]
@AlgumCorrupto ey bro did you fix that problem, I have the same problem

**Comment by AlgumCorrupto** [comment]
@pro470 nope

**Comment by pro470** [comment]
damn does the rest work for you because I'm new to this config I think the problem lay in the UpdateRemotePlugin call I guess it doesn't do the right thing because I get the same output as you when I run it I tried to change the content but when I reran it the call changes it back is there something we need to download to get UpdateRemotePlugin to work @AlgumCorrupto

**Comment by pro470** [comment]
found the problem but didn't solve it now just updating UpdateRemotePlugins doesn't find the rplugin folder in the wilder.nvim directory the actual output of the UpdateRemotePlugins should be in the rplugin.vim

" perl plugins


" node plugins


" python3 plugins
call remote#host#RegisterPlugin('python3', 'C:/Users/reyno/AppData/Local/nvim-data/lazy/wilder.nvim/rplugin/python3/wilder', [
      \ {'sync': v:true, 'name': '_wilder_python_basic_highlight', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_clap_filt', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_cpsm_filt', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': '_wilder_python_cpsm_highlight', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_difflib_sort', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_file_finder', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_fruzzy_filt', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_fuzzy_filt', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_fuzzywuzzy_sort', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': '_wilder_python_get_file_completion', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_get_help_tags', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_get_users', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': '_wilder_init', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': '_wilder_python_pcre2_highlight', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_search', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_sleep', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_lexical_sort', 'type': 'function', 'opts': {}},
      \ {'sync': 'urgent', 'name': '_wilder_python_uniq_filt', 'type': 'function', 'opts': {}},
     \ ])
 

" ruby plugins


https://pastebin.com/s2SEEarQ

but I still get the new error no notification handler registered for ... 
when I copy the pastebin code and change the directory to wilder

so to fix the problem we need to know why UpdateRemotePlugins doesn't find the rplugin in the wilder folder which is also in the runtimepath where UpdateRemotePlugins should look 

I also found that in pynvim config saying updateRemotePlugins only looks in the path rplugin/python3 which wilder has so I don't understand why it isn't finding the folder

**Comment by AlgumCorrupto** [comment]
I've stopped caring about trying to fix this but what i can remember is only a wilder problem, - that plugin wasn't updated in a long time. I'll try to have a look at this in detail later

**Comment by AlgumCorrupto** [comment]
@pro470 my suggestion is in the wilder plugin change every occurrence of python3 to just python
