### ISSUE TITLE
treesitter not finding lua parser

### ISSUE THREAD

**Issue by bldur** [jdhao/nvim-config#278]
> Error while calling lua chunk: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:107: no parser for 'lua
> ' language, see :help treesitter-parsers

This seem to be the only informative explanation:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279293

**Comment by bldur** [comment]
Only have this for Lua, and could be runtimepath internals as neovim 0.10 thing, was hoping you would know.

**Comment by jdhao** [comment]
I do not have issues on macOS. Maybe it is only issue on your system?
