### ISSUE TITLE
Typo on Nvim-qt Article

### ISSUE THREAD

**Issue by xolio** [jdhao/nvim-config#3]
On this page: https://jdhao.github.io/2019/01/17/nvim_qt_settings_on_windows/#where-should-i-put-configurations-related-to-nvim-qt ,  under "General settings" -> "Where should I put configurations related to nvim-qt?", the command <code>:echo stdpath('cofnig') </code> should instead read <code>:echo stdpath('config') </code>

**Comment by jdhao** [comment]
Thanks for pointing out the typo. I will fix it when I have got time.
