### ISSUE TITLE
nvim +PackerSync +qall does nothing

### ISSUE THREAD

**Issue by FrankFang** [jdhao/nvim-config#30]
Run `nvim +PackerSync +qall` and I get nothing but a screen flash. The plugins are not downloaded.

**Comment by FrankFang** [comment]
https://github.com/junegunn/vim-plug/issues/225

**Comment by FrankFang** [comment]
Workaround 
```
nvim +PackerSync +30sleep +qall
```

**Comment by jdhao** [comment]
That is indeed the case, because `PackerSync` seems asynchronous so nvim will quit immediately.

**Comment by jdhao** [comment]
@FrankFang  A better way to deal with asynchronous nature of Packer command, see https://github.com/jdhao/nvim-config/issues/31.
