### ISSUE TITLE
improve plugin auto install

### ISSUE THREAD

**Issue by jdhao** [jdhao/nvim-config#31]
Packer's operations are asynchronous. Previously, to install plugins in a non-interactive way, the following command is used:

```
nvim +PackerSync +30sleep +quitall
```

it is not ideal since we do not really know that after 30 seconds, the plugin installation process should finish.

A more idea way is to use autocmd  [`PackerComplete`](https://github.com/wbthomason/packer.nvim/blob/master/doc/packer.txt#L479) provided by Packer:

```
nvim -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```

**Comment by FrankFang** [comment]
RUN nvim -c 'autocmd User PackerComplete quitall' in Dockerfile got
```
packer_compile.lua not found: run PackerSync to fix!
[everforest] Generated /root/.local/share/nvim/site/pack/packer/opt/everforest/after/ftplugin
Press ENTER or type command to continue
```
