### ISSUE TITLE
UI: linux number not right

### ISSUE THREAD

**Issue by hxzhao527** [jdhao/nvim-config#32]
Problem:
![image](https://user-images.githubusercontent.com/8402502/145661757-b9563d3a-6dec-4f0d-ae3b-36ce0de418ed.png)

Host Info:
![image](https://user-images.githubusercontent.com/8402502/145661817-21517616-c45a-4d10-b975-6a5e495c4cf6.png)

```bash
❯ nvim -v
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by jdhao** [comment]
Everything is working normally. I have turned on both option number and relativenumber.


Please read the doc first (`:help number`  and `h relativenumber`).

See also https://jdhao.github.io/2019/01/11/line_number_setting_nvim/.
