### ISSUE TITLE
I am getting this error while editing an Md file. Anyone can possibly know the solution to this?

### ISSUE THREAD

**Issue by hhammoud01** [jdhao/nvim-config#34]
![image](https://user-images.githubusercontent.com/14010745/146641356-4727b1eb-9e89-475f-91ce-622f890a4dbf.png)

**Comment by jdhao** [comment]
Add the details of this issue. Or I can not help you.

**Comment by hhammoud01** [comment]
![image](https://user-images.githubusercontent.com/14010745/146642591-a27599c7-98b1-4667-b7a3-e301c95863c1.png)

Here is some information:
- Macbook 2021 M1 chip
- python 3.8.12
- output of pip freeze:
```
greenlet==1.1.2
jedi==0.18.1
msgpack==1.0.3
parso==0.8.3
pluggy==1.0.0
pynvim==0.4.3
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.3.3
ujson==5.0.0
```

**Comment by jdhao** [comment]
How to reproduce your issue?

**Comment by hhammoud01** [comment]
> How to reproduce your issue?

@jdhao It turned out I was using a pyenv environment (python virtual environment). When I install "pynvim" using pip, the error is gone (the first screenshot, whenever I start typing). But the "lspconfig" error is still there (second screenshot).
The only error now is when i perform ":checkhealth" is the one showing in the second screenshot.

**Comment by jdhao** [comment]
Have you installed [lua-language-server](https://github.com/sumneko/lua-language-server)?

**Comment by jdhao** [comment]
what is the output of `which lua-language-server`?

**Comment by hhammoud01** [comment]
> what is the output of `which lua-language-server`?

Command not found. I have been trying to install it for 2 hours now :) Any step by step guides?

**Comment by jdhao** [comment]
> > what is the output of `which lua-language-server`?
> 
> Command not found. I have been trying to install it for 2 hours now :) Any step by step guides?
> 

check the official doc, brew can install it? I suppose

**Comment by hhammoud01** [comment]
> 

Docs say nothing about brew, but brew indeed installed it and the error is gone. You are one king.
Now second step comes in: learning to use the plugins 👯‍♂️

**Comment by jdhao** [comment]
Pleaee reward the project with a star if you find it helpful.
