### ISSUE TITLE
Issue with gitsigns package

### ISSUE THREAD

**Issue by hhammoud01** [jdhao/nvim-config#343]
- `nvim --version`: NVIM v0.10.2 / Build type: Release / LuaJIT 2.1.1727870382.
- terminal emulator and version: Iterm 2 build 3.5.5
- Operating system/version: MacOS Version 13.0.1 (22A400) (VENTURA)
- Have you read and followed all steps in the [doc](https://github.com/jdhao/nvim-config/tree/master/docs): Yes
- Output of command `set runtimepath`: None

**Describe the bug**

Error executing vim.schedule lua callback: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:105: The coroutine failed with this message: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:180: attempt to call upvalue '
func' (a number value)
stack traceback:
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua: in function 'attach'
        ...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:132: in function 'setup_attach'
        ...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:191: in function <...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:167>
stack traceback:
        [C]: in function 'error'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:105: in function 'cb'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:140: in function <...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:139>

It seems that there is an issue with gitsigns package. The error appears "only occasionally" (every 5-6 times I open nvim).
After pressing any key when I get the error, It disappears.

Steps to reproduce the issue:

1. Open nvim every 4-5 times.

**Expected behavior**
Not getting the error on start.

**Screenshots**
![image](https://github.com/user-attachments/assets/c1f470b1-8aec-473e-a3b3-7434db2cb813)

**Comment by jdhao** [comment]
I haven't seen this issue myself. Maybe it is related to your environment. Please report to gitsigns instead.
