### ISSUE TITLE
setup for nodejs/js/ts

### ISSUE THREAD

**Issue by bharadwajduggaraju** [jdhao/nvim-config#35]
I want to integrate nodejs/js/ts autocomplete and syntax highlighting into this nvim setup for personal use. could you help me do so or tell me what I need to install and add to the config to get it to work?

**Comment by jdhao** [comment]
Add ts related plugins in `lua/plugins.lua`.

Install relevant language server and add it in `lua/config/lsp.lua`.

This should be all you need to do.

**Comment by bharadwajduggaraju** [comment]
Could you give me an example of what plugins to add and how to map them and get them to work cause I tried to install coc.nvim and add it to the plugins.lua and it doesnt seem to be autocompleting. I'm just wondering how to even get javascript/node.js autcomplete up and running similar to how well python files are handled.

**Comment by jdhao** [comment]
> @jdhao Could you give me an example of what plugins to add and how to map them and get them to work cause I tried to install coc.nvim and add it to the plugins.lua and it doesnt seem to be autocompleting. I'm just wondering how to even get javascript/node.js autcomplete up and running similar to how well python files are handled.

I am sorry. I have no expertise in javascript and related stuff. Maybe you can try [other configs which target at front end development](https://github.com/search?q=nvim+config+typescript).

**Comment by bharadwajduggaraju** [comment]
Okay, I'll check them out, thanks for your help!
