### ISSUE TITLE
Can anyone confirm/reject if there are problems with :PackerSync or any of the installation/funtionalities?

### ISSUE THREAD

**Issue by VProfirov** [jdhao/nvim-config#37]
nvim version: 0.6.1

I am tracking the Packer project status too, but there is conflicting information there about the situation regard Sync; Install and update of the nvim packages.

The error I get is 503 on the pull of the plugins from their repos

**Comment by jdhao** [comment]
> nvim version: 0.6.1
> 
> I am tracking the Packer project status too, but there is conflicting information there about the situation regard Sync; Install and update of the nvim packages.
> 
> The error I get is 503 on the pull of the plugins from their repos

which repo are you refering to? What error are you getting? Any screem shot or error message?

**Comment by VProfirov** [comment]
Please excuse my tardiness @jdhao, I was preoccupied.

In short, during :PackerUpdate each installed package was returning a 503 error. 
For more information, you can **refer to the updated information in the issue's header**

**Comment by jdhao** [comment]
okay, previously I am using fastgit as the mirror site for github. However, fastgit may not be reliable enough. Hence the error you see.  Now I use github by default.
