### ISSUE TITLE
How do I bind a title to the nvim-qt window

### ISSUE THREAD

**Issue by rerrabolu** [jdhao/nvim-config#38]
Currently when I open a file in nvim-qt it simply says "Neovim" of the nvim graphical window. I would like to associate the window to a specific Title. Any suggestions / ideas to help.

When I do the same thing in gvim it will show the filename in the graphical window

**Comment by rerrabolu** [comment]
Just to add results of my experiment:

- Make sure nvim config file "init.vim" does not define the parameter "title"
- Define the parameter "title" for nvim-qt in its config file "ginit.vim"
- e.g.  set title

Once I did I was able to see nvim-qt window show filename in its title bar. Don't know how all of these things are inter-related. Happy to have it working.

**Comment by jdhao** [comment]
hi, @rerrabolu, once you open a file, this config will show the file path and last-modified time on the title bar. For example, if i open my `init.vim`, I see the following text on the title bar:

> ~\AppData\Local\nvim\init.vim 2022-01-21 10:40 - Neovim

Is this what you are seeing?

**Comment by rerrabolu** [comment]
I am on linux ubuntu system. I see the file name followed by the folder in which it exists.

e.g.  temp.c (~/Downloads) - NVIM -- Neovim

I am satisfied with my current setup i.e. it shows me the filename. What I would like is passing a cmdline arg to bind as the title for the window.

**Comment by jdhao** [comment]
Are you using this config? The title format seems wrong if you are using this config.

When you are inside nvim-qt, run comamnd `set titlestring?`, what is the output?

**Comment by rerrabolu** [comment]
It seems the variable is not defined. When I run "set titlestring?" I get "titlestring=". However as I said earlier I see the filename and the folder it is in.

I am not well versed in the various options/commands of vim neovim. I rely on a few basic things to get my work done. In this regard it is fair to say that the time and effort it takes to get a good and powerful work env in vim/neovim is terrible. If it were a product charging me they will be out of business :-)

I don't know when and how long it will be before simple tools such as vim/neovim can mature. The alternative is going to vscode and other IDE's.

**Comment by jdhao** [comment]
Are you using this config? It is weird that `titlestring` is not set if that is the case.

**Comment by rerrabolu** [comment]
Could you explain as to what you mean by this "config?" Are you referring to ginit.vim from your repo. If so I am not using it. I could give it a shot for testing and let you know

**Comment by jdhao** [comment]
> Could you explain as to what you mean by this "config?" Are you referring to ginit.vim from your repo.

I mean if you are using the whole repo? Otherwise, I am not sure why do you open an issue here...
