### ISSUE TITLE
Error on changing colorscheme

### ISSUE THREAD

**Issue by powrhouseofthecell** [jdhao/nvim-config#39]
![Screenshot (1)](https://user-images.githubusercontent.com/67638966/151695389-e7abdf7d-847b-4815-9c61-583aa09faa32.png)

**Comment by jdhao** [comment]
this config will load a colorscheme at random when starting. This is how it works for me.

If you want to use a fixed colorscheme, change the file core/themes.vim, specifically [this line](https://github.com/jdhao/nvim-config/blob/master/core/themes.vim#L72), change the variable `s:theme` to a fixed theme.
