### ISSUE TITLE
[Question] How to auto format vimscript

### ISSUE THREAD

**Issue by jiarui-z** [jdhao/nvim-config#40]
老哥想请教一下你是怎么自动format vimscript的，我看到这个snippet觉得应该不是手动换行的吧？我找了一些资料，但没看到什么可以把一个长的行字懂格式化成像这段代码一样？

感谢🙏
```
let s:core_conf_files = [
      \ 'globals.vim',
      \ 'options.vim',
      \ 'autocommands.vim',
      \ 'mappings.vim',
      \ 'plugins.vim',
      \ 'themes.vim'
      \ ]
```

**Comment by jdhao** [comment]
据我所知，vim script 好像没有自动 format 工具。不过你写 vim script 时候，就有一些 自动 indent 的功能，你发的这段的确是手写配合自动 indent 完成的，并没有用到 外部 format 工具。

如果喜欢自动 format，建议往 lua 配置转，lua 的 format 比 viml 好很多。
