### ISSUE TITLE
LeaderF not working

### ISSUE THREAD

**Issue by zendevil** [jdhao/nvim-config#41]
- `nvim --version`: NVIM v0.6.0
- terminal emulator and version: iTerm
- Operating system/version: macOS Monterey

**Describe the bug**

Can't use `<leader> f f` to access LeaderF.

1. Do `<leader> f f`

**Expected behavior**

LeaderF is supposed to show.

**Screenshots**
`<leader> f` does show the following. But doing another f just silently does nothing.
<img width="1455" alt="Screen Shot 2022-02-11 at 4 15 57 AM" src="https://user-images.githubusercontent.com/30054030/153565392-39766843-d37d-4b58-8512-75ecf30e2d6a.png">

**Comment by zendevil** [comment]
Yes nothing happens when I run this.

**Comment by jdhao** [comment]
> Yes nothing happens when I run this.

You have not run command `PakcerSync` to install plugins, have you？

**Comment by zendevil** [comment]
Yes, have run PackerSync. And LeaderF is installed under that directory.

  LeaderF
    .git
    .github
    autoload
    doc
    plugin
    syntax
    .gitignore
    CHANGELOG.md
    install.bat
    install.sh
    ISSUE_TEMPLATE.md
    LICENSE
    README.md


**Comment by jdhao** [comment]
Restart nvim and see if `Leaderf file --popup` works and if it does not, what you see.

Also paste the output of `set &runtimepath` after using the above command.

**Comment by zendevil** [comment]
After startin nvim when I run Leaderf file --popup, nothing happens. And set &runtimepath shows:
```
E518: Unknown option: &runtimepath
```

**Comment by jdhao** [comment]
My bad, it should be `set runtimepath`

**Comment by zendevil** [comment]
runtimepath=~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,~/.local/share/nvim/site/pack/p
acker/opt/cmp-buffer,~/.local/share/nvim/site/pack/packer/opt/cmp-nvim-lua,~/.local/share/nvim/site
/pack/packer/opt/nvim-lspconfig,~/.local/share/nvim/site/pack/packer/opt/cmp-nvim-lsp,~/.local/shar
e/nvim/site/pack/packer/opt/cmp-path,~/.local/share/nvim/site/pack/packer/opt/cmp-emoji,~/.local/sh
are/nvim/site/pack/packer/opt/nvim-cmp,~/.local/share/nvim/site/pack/packer/opt/lspkind-nvim,~/.loc
al/share/nvim/site/pack/packer/opt/vim-asterisk,~/.local/share/nvim/site/pack/packer/opt/bufferline
.nvim,~/.local/share/nvim/site/pack/packer/opt/lualine.nvim,~/.local/share/nvim/site/pack/packer/op
t/unicode.vim,~/.local/share/nvim/site/pack/packer/opt/vim-yoink,~/.local/share/nvim/site/pack/pack
er/opt/vim-repeat,~/.local/share/nvim/site/pack/packer/opt/AutoSave.nvim,~/.local/share/nvim/site/p
ack/packer/opt/indent-blankline.nvim,~/.local/share/nvim/site/pack/packer/opt/alpha-nvim,~/.local/s
hare/nvim/site/pack/packer/opt/targets.vim,~/.local/share/nvim/site/pack/packer/opt/hop.nvim,~/.loc
al/share/nvim/site/pack/packer/opt/open-browser.vim,~/.local/share/nvim/site/pack/packer/opt/vim-co
mmentary,~/.local/share/nvim/site/pack/packer/opt/nvim-web-devicons,~/.local/share/nvim/site/pack/p
acker/opt/whitespace.nvim,~/.local/share/nvim/site/pack/packer/opt/which-key.nvim,~/.local/share/nv
im/site/pack/packer/opt/vim-swap,~/.local/share/nvim/site/pack/packer/opt/vim-sandwich,~/.local/sha
re/nvim/site/pack/packer/opt/vim-matchup,~/.local/share/nvim/site/pack/packer/opt/vim-indent-object
,~/.local/share/nvim/site/pack/packer/opt/vim-highlighturl,~/.local/share/nvim/site/pack/packer/opt
/neoscroll.nvim,~/.local/share/nvim/site/pack/packer/opt/vim-fugitive,~/.local/share/nvim/site/pack
/packer/opt/nvim-treesitter,~/.local/share/nvim/site/pack/packer/opt/nvim-notify,~/.local/share/nvi
m/site/pack/packer/opt/vim-signify,~/.local/share/nvim/site/pack/*/start/*,~/.local/share/nvim/site
/pack/packer/opt/gruvbox-material,~/.local/share/nvim/site/pack/packer/opt/wilder.nvim,~/.local/sha
re/nvim/site/pack/packer/opt/firenvim,~/.local/share/nvim/site/pack/packer/opt/committia.vim,~/.loc
al/share/nvim/site/pack/packer/opt/packer.nvim,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr
/local/Cellar/neovim/0.6.0/share/nvim/runtime,/usr/local/Cellar/neovim/0.6.0/lib/nvim,~/.local/shar
e/nvim/site/pack/packer/opt/cmp-buffer/after,~/.local/share/nvim/site/pack/packer/opt/cmp-nvim-lua/
after,~/.local/share/nvim/site/pack/packer/opt/cmp-nvim-lsp/after,~/.local/share/nvim/site/pack/pac
ker/opt/cmp-path/after,~/.local/share/nvim/site/pack/packer/opt/cmp-emoji/after,~/.local/share/nvim
/site/pack/packer/opt/vim-sandwich/after,~/.local/share/nvim/site/pack/packer/opt/vim-matchup/after
,~/.local/share/nvim/site/pack/packer/opt/nvim-treesitter/after,~/.local/share/nvim/site/pack/packe
r/opt/gruvbox-material/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,~/.local/s
hare/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after

**Comment by jdhao** [comment]
Have you followed the instructions here: https://github.com/jdhao/nvim-config/tree/master/docs?

Apparently, LeaderF is not on the runtime path. 

I can not reproduce your issue.
