### ISSUE TITLE
Wilder autocomplete not working 

### ISSUE THREAD

**Issue by zendevil** [jdhao/nvim-config#42]
- `nvim --version`: 0.6.0
- terminal emulator and version: iTerm
- Operating system/version: macOS Monterey

**Describe the bug**

1. do `:tabedit ./<tab>`

**Expected behavior**
Should show the potential paths, but instead nothing happens.

**Comment by jdhao** [comment]
Are you opening nvim and immediately running the command or something else?

**Comment by jdhao** [comment]
Also try https://github.com/jdhao/nvim-config/commit/295f47b1fb1b8a56832400f672b8c7b9746684d0. It may *solve* this issue.

**Comment by zendevil** [comment]
that change didn't work. Btw, getting this too in the bar:  Unknown function: _wilder_python_get_file_completion

**Comment by jdhao** [comment]
It seems you haven't properly set up this configurattion. It is quite complicated and not suitable for beginners if you have not follow the docs carefully.

The main cause may be the same as https://github.com/jdhao/nvim-config/issues/41.

Closed this for now.
