### ISSUE TITLE
Seeing an error pop up when using

### ISSUE THREAD

**Issue by zendevil** [jdhao/nvim-config#43]
- `nvim --version`: 0.6.0
- terminal emulator and version: iTerm
- Operating system/version: macOS Monterey

**Describe the bug**

1. Just type something in nvim

**Expected behavior**
Stuff just types

**Screenshots**
<img width="1455" alt="Screen Shot 2022-02-11 at 7 10 33 AM" src="https://user-images.githubusercontent.com/30054030/153589304-f8ba1870-3150-4f35-96b4-d0122f030707.png">

**Comment by jdhao** [comment]
I have seen this error once, but have not been able to reproduce it for a long time. I think it may be a bug of some plugins. Can not reproduce on my macOS now.
