### ISSUE TITLE
How to change mouse behaviour?

### ISSUE THREAD

**Issue by mihneaCR** [jdhao/nvim-config#45]
Hi, i just installed your config and am trying it out currently, like it a lot.
I was wondering how i can disable the entering of visual mode when moving the mouse.
This happens after the first time that i select text with the mouse like normal, afterwards every movement of the mouse enters visual mode and starts selecting text. How can i change it back, so that it only starts selecting when actually pressing the mouse button?
Also, do you know how to re-enable the arrow keys in visual mode? i am using a 60% keyboard, so the arrow keys are accessible to me quickly.
Thanks for taking the time to make this config, it is really well thought out

**Comment by jdhao** [comment]
Please fill out the bug template,  they exist for a reason.  Otherwise, I cannot reproduce your issue.

**Comment by mihneaCR** [comment]
It was not a bug in that case, rather an issue with the configuration not being correct for my taste. I managed to fix it myself by adding the following to the config file:
set mouse=nicr
set mouse=a
Thanks for this config however, it is a great starting point!
You can close this issue

**Comment by jdhao** [comment]
You do not need to set an option multiple times like this. The latter will override the former. I am glad that you have solved your issue.

This config servers as a reference, it is not intended to be used verbatim, as is stated in init.vim 😅

**Comment by Gxnum** [comment]
> I managed to fix it myself by adding the following to the config file:

In which file did you add the following?
