### ISSUE TITLE
No Syntax Highlighting, Help Me

### ISSUE THREAD

**Issue by VilosmZX** [jdhao/nvim-config#49]
- `nvim --version`: 0.6.0
- terminal emulator and version: 
- Operating system/version: Windows 10

**Describe the bug**
No Syntax Highlighting

**Screenshots**
![image](https://user-images.githubusercontent.com/70438760/163718324-f68b7828-dc11-4d53-9b91-26460cb5a1a6.png)

**Comment by jdhao** [comment]
Have you even read the readme before asking?

**Comment by VilosmZX** [comment]
help me

**Comment by jdhao** [comment]
only nvim 0.7 is supported. Please read the doc before opening an issue.
