### ISSUE TITLE
VimTex Deprecated setting

### ISSUE THREAD

**Issue by jahanbani** [jdhao/nvim-config#50]
- `nvim --version`: 0.8
- terminal emulator and version: Nvy.exe
- Operating system/version: Windows
- Have you read and followed all steps in the [doc](https://github.com/jdhao/nvim-config/tree/master/docs): Yes
- Output of command `set runtimepath`:

**Describe the bug**

Opening any `.tex` file will generate the below warning:
![image](https://user-images.githubusercontent.com/16143553/166121708-ba93ebc9-0166-45a5-a166-2ecd16d2f049.png)

Steps to reproduce the issue:

1. Open any .tex file

**Expected behavior**
Not to see any warnings

**Comment by jdhao** [comment]
can you reproduce with 0.7? Only stable version is supported.

**Comment by jahanbani** [comment]
Yes. I get the same error :(
