### ISSUE TITLE
Running nvim gives error

### ISSUE THREAD

**Issue by fasetto** [jdhao/nvim-config#51]
- `nvim --version`: NVIM v0.6.1
- terminal emulator and version: iTerm Build 3.4.15
- Operating system/version: macOS
- Have you read and followed all steps in the [doc](https://github.com/jdhao/nvim-config/tree/master/docs): Yes
- Output of command `set runtimepath`:

```
 runtimepath=~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,~/.local/share/nvim/site/
pack/*/start/*,~/.local/share/nvim/site/pack/packer/opt/vim-gruvbox8,~/.local/share/nvim/site
/pack/packer/opt/wilder.nvim,~/.local/share/nvim/site/pack/packer/opt/committia.vim,~/.local/
share/nvim/site/pack/packer/opt/firenvim,~/.local/share/nvim/site/pack/packer/opt/packer.nvim
,/usr/local/share/nvim/site,/usr/share/nvim/site,/opt/homebrew/Cellar/neovim/0.6.1/share/nvim
/runtime,/opt/homebrew/Cellar/neovim/0.6.1/lib/nvim,/usr/share/nvim/site/after,/usr/local/sha
re/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after
```

**Describe the bug**

Every time I run `nvim` it gives the error below;
```
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Error in packer_compiled: /Users/serkan/.config/nvim/lua/config/nvim-tree.lua:116: attempt to
 index field 'keymap' (a nil value)
Please check your config for correctness
Colorscheme: gruvbox_material
Press ENTER or type command to continue
```

Steps to reproduce the issue:

1. Run nvim

**Expected behavior**
Run without error

**Comment by jdhao** [comment]
Have you checked the readme? Only nvim 0.7 is supported.

**Comment by fasetto** [comment]
I installed nvim using homebrew. I tought it will install the latest stable release. Now I checked and latest is 0.7. 🤦‍♂️
Sorry.

**Comment by mr-cal** [comment]
Upgrading to Ubuntu 22.04 broke my nvim config.  I tried with the latest version of `nvim-config` and got the same error as @fasetto.  I spun my wheels for awhile before finding this issue and realizing I was on nvim-0.6.1. 

A warning check in the vimscript could be useful, (i.e. `if !has('nvim-0.7') | echo "nvim-0.7 required!"`)

**Comment by jdhao** [comment]
Personally, I just use the nvim binary release to get rid of the pain of using the system package manager.  You can also use a small script to automate this.
