### ISSUE TITLE
Ultisnips hiccup in insert mode

### ISSUE THREAD

**Issue by medwatt** [jdhao/nvim-config#52]
I have a question with regards to ultisnips. When I enter insert mode for the first time, I always notice that the cursor momentarily freezes even though ultisnips is not being lazy-loaded. Do you also observe this issue, and if yes, do you have a solution?

**Comment by jdhao** [comment]
> I always notice that the cursor momentarily freezes even though ultisnips is not being lazy-loaded. Do you also observe this issue,

Ultisnips is set to be lazy-loaded using `InsertEnter` event.

**Comment by medwatt** [comment]
> > I always notice that the cursor momentarily freezes even though ultisnips is not being lazy-loaded. Do you also observe this issue,
> 
> Ultisnips is set to be lazy-loaded using `InsertEnter` event.

I know, but because of the hiccup when entering insert mode, I decided to try to not lazyload it, but the problem persists. Do you experience the same issue?

**Comment by jdhao** [comment]
The completion is almost instant for me, I experience no major lag after entering insert mode. As soon as I start inputing characters, the ultinips snippet is showing in the completion menu. I think it may be related to your specific setup or your environment.
