### ISSUE TITLE
nvim 0.8 tracking

### ISSUE THREAD

**Issue by jdhao** [jdhao/nvim-config#53]
1. change in LSP table keys
  see https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767 .

2. default changed to filetype.lua
  See https://github.com/neovim/neovim/issues/14090#issuecomment-1177933661 .

3. indexed `vim.cmd`
  https://github.com/neovim/neovim/commit/559ef3e90393a8f02c8350a9d60f4b7849815d97.

4. zero cmdheight:
  https://github.com/neovim/neovim/commit/663cbe2620278eae658895f82f3eb9bc89310e73

5. measure require() in --startuptime
  https://github.com/neovim/neovim/commit/2c739431e8e5a2aacc39ef429401f5e4427d027a

6. preview for user-created function
  https://github.com/neovim/neovim/commit/46536f53e82967dcac8d030ee3394cdb156f9603

7. hl group `CurSearch`
  https://github.com/neovim/neovim/commit/b16afe4d556af7c3e86b311cfffd1c68a5eed71f

8. `:map`, `:command`, `:au` can print lua source location
  https://github.com/neovim/neovim/commit/3df8d9b8c56a7f0af0f7590b11831bd96ead92f1

9. Nvim build env for Linux updated to Ubuntu 20.04, so the nightly release may not work for old machines any more. I tested latest nightly on CentOS 7.4, it can not work anymore, showing the following error:

    > /lib64/libc.so.6: version `GLIBC_2.28' not found

    see also https://github.com/neovim/neovim/commit/48241c3b238e0cf5b4b5af61db4e54f2b8c02897

https://github.com/neovim/neovim/issues/19711#issuecomment-1266144004

10. `vim.opt` or `vim.o`?

    https://github.com/neovim/neovim/pull/19477#issuecomment-1194040328
    https://github.com/neovim/neovim/pull/19982
    https://github.com/neovim/neovim/issues/20107

11. `:Man` ported to lua
    https://github.com/neovim/neovim/pull/19912

12. hijack message
    https://github.com/neovim/neovim/pull/16396

13. Clickable statusline
    https://github.com/neovim/neovim/pull/18650

**Comment by max397574** [comment]
treesitter based spell checking

**Comment by BoaPi** [comment]
@max397574 is there an issue for that or where can I find more information about tree-sitter based spell checking?

**Comment by tbung** [comment]
See here wrt treesitter spelling: https://github.com/neovim/neovim/pull/19419

**Comment by jdhao** [comment]
Treesitter parser for help doc is currently having some issue for conceal: https://github.com/neovim/tree-sitter-vimdoc/issues/23.
