### ISSUE TITLE
Arrow Keys not working, only work on INSERT mode.

### ISSUE THREAD

**Issue by Gxnum** [jdhao/nvim-config#54]
I am not *sure* if this is a bug or a feature (probably a feature) but I want to know the name of the plugin that adds the ability to use the cursor with a mouse, basically wherever you click, the cursor goes there. Although that plugin may be helpful for others, it is annoying, and I would love to know how to remove it. However, the arrow keys, which I find very useful, do work on **INSERT** mode. If it isn't a feature, and rather a bug, then consider this an Issue.

**Comment by Gxnum** [comment]
I should have read the previous closed Issues...

**Comment by jdhao** [comment]
Based on your question, I think you know little about nvim or vim. The mouse behavior is not based on any plugin, it can be changed using the `mouse` option. I set it in `core/options.vim`.

> However, the arrow keys, which I find very useful, do work on INSERT mode

Using arrow keys in insert mode or normal mode (to move your cursors) is simply wrong.  You should learn some decent ways to move your cursor in normal mode, not using the arrow keys, which is highly inefficient. If you like to use arrow key often, you can just use vs code.

To answer your direct question, arrow keys in normal mode do work, it is just I have mapped them to do other things (switching the windows), see [mapping here](https://github.com/jdhao/nvim-config/blob/99d5a0343b288ec82dc4e43ee5c689c5f5b31960/core/mappings.vim#L159-L162).

**Comment by Gxnum** [comment]
Thank you so much for your reply. I should have checked mappings.vim...

**Comment by mobergmann** [comment]
> Based on your question, I think you know little about nvim or vim. The mouse behavior is not based on any plugin, it can be changed using the `mouse` option. I set it in `core/options.vim`.
> 
> > However, the arrow keys, which I find very useful, do work on INSERT mode
> 
> Using arrow keys in insert mode or normal mode (to move your cursors) is simply wrong. You should learn some decent ways to move your cursor in normal mode, not using the arrow keys, which is highly inefficient. If you like to use arrow key often, you can just use vs code.
> 
> To answer your direct question, arrow keys in normal mode do work, it is just I have mapped them to do other things (switching the windows), see [mapping here](https://github.com/jdhao/nvim-config/blob/99d5a0343b288ec82dc4e43ee5c689c5f5b31960/core/mappings.vim#L159-L162).

Even if using the arrow keys might be bad practice, to avoid them doesn't answer the question (even if it might be good advice).
To disable the arrow keys you need to, e.g. comment the [next few](https://github.com/jdhao/nvim-config/blob/18abfa775499f6e929632f577fee5c3f50c6f2f6/core/mappings.lua#L163) lines (quiet self explainable).
