### ISSUE TITLE
Error after following installation steps

### ISSUE THREAD

**Issue by hasanramp** [jdhao/nvim-config#65]
- `nvim --version`: ```v0.7.2``` 
- 
- terminal emulator and version: alacritty and 0.10.1
- Operating system/version: ubuntu 22.04
- Have you read and followed all steps in the [doc](https://github.com/jdhao/nvim-config/tree/master/docs): yes
- Output of command `set runtimepath`:

  
  ```

  ```

**Describe the bug**

Steps to reproduce the issue:

1. follow install instructions
2. open neovim
3.

**Expected behavior**

No errors should be there
**Screenshots**

![image](https://user-images.githubusercontent.com/81405807/184866173-ec921c9e-6317-4e5e-9b2e-5a0391d8de42.png)

**Additional context**
```Error```:<br>
```
Error detected while processing /home/hasan/.config/nvim/init
.lua:
E5113: Error while calling lua chunk: /home/hasan/.config/nvi
m/init.lua:36: Vim(echoerr):Python 3 executable not found! Yo
u must install Python 3 and set its PATH correctly!
stack traceback:
        [C]: in function 'cmd'
        /home/hasan/.config/nvim/init.lua:36: in main chunk
Press ENTER or type command to continue
```

**Comment by jdhao** [comment]
what error? Please fill the template.

**Comment by hasanramp** [comment]
> what error? Please fill the template.

yeah sorry. I accidentally hit enter after typing the title

**Comment by jdhao** [comment]
The error message is pretty straight forward, you need to have `python` on your path. The check is [here](https://github.com/jdhao/nvim-config/blob/master/core/globals.vim#L23-L31). 

Also check [this part](https://github.com/jdhao/nvim-config/tree/master/docs#python) of doc about python3.
